
export const rows = [
    {
      id: 1,
      rfc: "HEMA981206TR6",
      nombre: "Alexis",
      paterno: "Hernandez",
      materno: "Mondragon",
      razonSocial: "Empresa de Software",
      sucursal: "Centro",
    },
    {
      id: 2,
      rfc: "SACD120112TR4",
      nombre: "Daniel",
      paterno: "Sanchez",
      materno: "Camacho",
      razonSocial: "Empresa de Software",
      sucursal: "Sur",
    },
    {
      id: 3,
      rfc: "BEPP121212HT6",
      nombre: "Pablo",
      paterno: "Benitez",
      materno: "Peña",
      razonSocial: "Empresa de Software",
      sucursal: "Este",
    },
    {
      id: 4,
      rfc: "GASM011210HYT",
      nombre: "Juan Manuel",
      paterno: "Garcia",
      materno: "Soto",
      razonSocial: "Empresa de Software",
      sucursal: "Oeste",
    },
    {
      id: 5,
      rfc: "OCCF123456YT7",
      nombre: "Francisco",
      paterno: "Ochoa",
      materno: "Campos",
      razonSocial: "Empresa de Software",
      sucursal: "Norte",
    },
    {
      id: 6,
      rfc: "COME101202GT4",
      nombre: "Ernesto",
      paterno: "Cortez",
      materno: "Mendez",
      razonSocial: "Empresa de Software",
      sucursal: "Centro",
    },
    {
        id: 7,
        rfc: "HEMA981206TR6",
        nombre: "Alexis",
        paterno: "Hernandez",
        materno: "Mondragon",
        razonSocial: "Empresa de Software",
        sucursal: "Centro",
      },
      {
        id: 8,
        rfc: "SACD120112TR4",
        nombre: "Daniel",
        paterno: "Sanchez",
        materno: "Camacho",
        razonSocial: "Empresa de Software",
        sucursal: "Sur",
      },
      {
        id: 9,
        rfc: "BEPP121212HT6",
        nombre: "Pablo",
        paterno: "Benitez",
        materno: "Peña",
        razonSocial: "Empresa de Software",
        sucursal: "Este",
      },
      {
        id: 10,
        rfc: "GASM011210HYT",
        nombre: "Juan Manuel",
        paterno: "Garcia",
        materno: "Soto",
        razonSocial: "Empresa de Software",
        sucursal: "Oeste",
      },
      {
        id: 11,
        rfc: "OCCF123456YT7",
        nombre: "Francisco",
        paterno: "Ochoa",
        materno: "Campos",
        razonSocial: "Empresa de Software",
        sucursal: "Norte",
      },
      {
        id: 12,
        rfc: "COME101202GT4",
        nombre: "Ernesto",
        paterno: "Cortez",
        materno: "Mendez",
        razonSocial: "Empresa de Software",
        sucursal: "Centro",
      },
      {
        id: 13,
        rfc: "HEMA981206TR6",
        nombre: "Alexis",
        paterno: "Hernandez",
        materno: "Mondragon",
        razonSocial: "Empresa de Software",
        sucursal: "Centro",
      },
      {
        id: 14,
        rfc: "SACD120112TR4",
        nombre: "Daniel",
        paterno: "Sanchez",
        materno: "Camacho",
        razonSocial: "Empresa de Software",
        sucursal: "Sur",
      },
      {
        id: 15,
        rfc: "BEPP121212HT6",
        nombre: "Pablo",
        paterno: "Benitez",
        materno: "Peña",
        razonSocial: "Empresa de Software",
        sucursal: "Este",
      },
      {
        id: 16,
        rfc: "GASM011210HYT",
        nombre: "Juan Manuel",
        paterno: "Garcia",
        materno: "Soto",
        razonSocial: "Empresa de Software",
        sucursal: "Oeste",
      },
      {
        id: 17,
        rfc: "OCCF123456YT7",
        nombre: "Francisco",
        paterno: "Ochoa",
        materno: "Campos",
        razonSocial: "Empresa de Software",
        sucursal: "Norte",
      },
      {
        id: 18,
        rfc: "COME101202GT4",
        nombre: "Ernesto",
        paterno: "Cortez",
        materno: "Mendez",
        razonSocial: "Empresa de Software",
        sucursal: "Centro",
      },
      {
        id: 19,
        rfc: "HEMA981206TR6",
        nombre: "Alexis",
        paterno: "Hernandez",
        materno: "Mondragon",
        razonSocial: "Empresa de Software",
        sucursal: "Centro",
      },
      {
        id: 20,
        rfc: "SACD120112TR4",
        nombre: "Daniel",
        paterno: "Sanchez",
        materno: "Camacho",
        razonSocial: "Empresa de Software",
        sucursal: "Sur",
      },
      {
        id: 21,
        rfc: "BEPP121212HT6",
        nombre: "Pablo",
        paterno: "Benitez",
        materno: "Peña",
        razonSocial: "Empresa de Software",
        sucursal: "Este",
      },
      {
        id: 22,
        rfc: "GASM011210HYT",
        nombre: "Juan Manuel",
        paterno: "Garcia",
        materno: "Soto",
        razonSocial: "Empresa de Software",
        sucursal: "Oeste",
      },
      {
        id: 23,
        rfc: "OCCF123456YT7",
        nombre: "Francisco",
        paterno: "Ochoa",
        materno: "Campos",
        razonSocial: "Empresa de Software",
        sucursal: "Norte",
      },
      {
        id: 24,
        rfc: "COME101202GT4",
        nombre: "Ernesto",
        paterno: "Cortez",
        materno: "Mendez",
        razonSocial: "Empresa de Software",
        sucursal: "Centro",
      },
  ];
